# Generated by Django 4.0.4 on 2022-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Applicant name'),
        ),
    ]
