# Generated by Django 4.0.4 on 2022-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0002_alter_applicant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='DateOfBirth',
            field=models.DateField(),
        ),
    ]
